name: sellout
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7

  dropdown_button2: ^2.3.9

  app_links: ^6.3.2

  intl: ^0.19.0

  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1

  flutter_dotenv: ^5.1.0
  provider: ^6.1.2
  path_provider: ^2.1.4

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  shared_preferences: ^2.3.2

  permission_handler: ^11.3.1

  photo_manager: ^3.4.0
  get_it: ^8.0.0
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.11
  hive_generator: ^2.0.1

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: "assets/icons/icon.png"
  image_path_ios: "assets/icons/sellout-bg.png"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  android: true
  ios: true
  color_dark: "#000000"
  color: "#ffffff"
  image: "assets/icons/icon.png"


flutter:
  uses-material-design: true
  assets:
    - prod.env
    - dev.env
    - assets/icons/
    - assets/images/
    - assets/jsons/
    - assets/translations/

  # example:
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
