name: sellout
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+9

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  dropdown_search: ^6.0.2
  dropdown_button2: ^2.3.9

  app_links: ^6.3.2

  intl: ^0.20.2

  carousel_slider: ^5.0.0
  cached_network_image: ^3.4.1

  flutter_dotenv: ^5.1.0
  provider: ^6.1.2
  path_provider: ^2.1.4

  hive: ^2.2.3
  hive_flutter: ^1.1.0

  shared_preferences: ^2.3.2

  permission_handler: ^12.0.0+1

  get_it: ^8.0.0
  flutter_html: ^3.0.0-beta.2
  crypto: ^3.0.6
  
  video_player: ^2.9.2
  flutter_contacts: ^1.1.9+2
  open_file: ^3.2.1
  saver_gallery: ^4.0.1


  flutter_sound: ^9.28.0
  audio_waveforms: ^1.0.5
  just_audio: ^0.10.4

  syncfusion_flutter_calendar: ^28.1.33

  google_maps_flutter: ^2.10.1
  geocoding: ^3.0.0
  flutter_hooks: ^0.21.2
  socket_io_client: ^3.1.2

  flutter_stripe: 11.0.0

  device_info_plus: ^10.0.1

  photo_manager: ^3.4.0
  camera: ^0.11.1
  image_picker: ^1.1.2
  emoji_picker_flutter: ^4.3.0
  file_picker: ^10.1.9
  mime: ^2.0.0

  http: ^1.4.0

  url_launcher: ^6.3.2
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  flutter_typeahead: ^5.2.0
  flutter_svg: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  build_runner: ^2.4.11
  hive_generator: ^2.0.1

  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: "assets/icons/icon.png"
  image_path_ios: "assets/icons/sellout-bg.png"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  android: true
  ios: true
  color_dark: "#000000"
  color: "#ffffff"
  image: "assets/icons/icon.png"


flutter:
  uses-material-design: true
  assets:
    - prod.env
    - dev.env
    - assets/icons/
    - assets/icons/svg_icons/
    - assets/icons/png_icons/
    - assets/audio/
    - assets/images/
    - assets/images/payment_methods/
    - assets/images/marketplace_filters/
    - assets/jsons/
    - assets/jsons/foot_brands.json
    - assets/jsons/clothes_brands.json
    - assets/translations/
    
  # example:
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
