name: sellout
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.2+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  dropdown_button2: ^2.3.9

  app_links: ^7.0.0

  intl: ^0.20.2
  flutter_typeahead: ^5.2.0
  carousel_slider: ^5.1.1
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0

  flutter_dotenv: ^6.0.0
  provider: ^6.1.5
  path_provider: ^2.1.5

  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0

  shared_preferences: ^2.5.3

  permission_handler: ^12.0.1

  get_it: ^9.1.1
  flutter_html: ^3.0.0
  crypto: ^3.0.7
  
  video_player: ^2.10.1
  open_file: ^3.5.10

  flutter_sound: ^9.30.0
  audio_waveforms: ^2.0.0
  just_audio: ^0.10.5

  syncfusion_flutter_calendar: ^31.2.15

  geocoding: ^4.0.0
  geolocator: ^14.0.2
  flutter_hooks: ^0.21.3
  socket_io_client: ^3.1.3

  flutter_stripe: ^12.1.1
  device_info_plus: ^12.3.0

  photo_manager: ^3.8.2
  camera: ^0.11.3
  image_picker: ^1.2.1
  emoji_picker_flutter: ^4.4.0
  file_picker: ^10.3.7
  mime: ^2.0.0
  http: ^1.6.0
  pdf: ^3.10.1
  printing: ^5.11.0

  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_pdfview: ^1.3.2
  flutter_custom_tabs: ^2.4.1
  url_launcher: ^6.3.2
  # url_launcher: ^6.2.5
  flutter_svg: ^2.2.3

  flutter_native_splash: ^2.4.7
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  analyzer: ^9.0.0

  build_runner: ^2.4.13
  hive_ce_generator: ^1.6.0

  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: assets/images/sellout_logo.png
  image_path_ios: assets/images/sellout_logo.png

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/sellout_logo.png

flutter_native_splash:
  android: true
  ios: true

  color: "#FFFFFF"
  color_dark: "#0E0E0E"

  image: assets/images/sellout_logo.png

  # Make sure the image is centered on Android
  android_gravity: center

  # Android 12+ requires separate config
  android_12:
    image: assets/images/sellout_logo.png
    color: "#FFFFFF"
    color_dark: "#0E0E0E"



flutter:
  uses-material-design: true
  assets:
    - prod.env
    - dev.env
    - assets/icons/
    - assets/icons/svg_icons/
    - assets/icons/png_icons/
    - assets/audio/
    - assets/images/
    - assets/images/payment_methods/
    - assets/images/marketplace_filters/
    - assets/images/sellout_team/
    - assets/jsons/
    - assets/translations/
    - assets/docs/
    - assets/docs/privacy_security/
    - assets/docs/seller-and_consumer_rights/
    - assets/docs/user_agreement_platform_rules/
    - assets/docs/intellectual_property/
    
  # example:
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/icons/AppIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
